USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[AGENT]    Script Date: 12/17/2010 11:49:02 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENT]') AND type in (N'U'))
DROP TABLE [dbo].[AGENT]


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[AGENT]    Script Date: 12/17/2010 11:34:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENT](
  [AGENT_PK] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [MPAN_LNK] [numeric](36, 0) NOT NULL,
  [J0092] [datetime] NULL,
  [J0094] [datetime] NULL,
  [J0163] [varchar](1) NULL,
  [J0178] [varchar](4) NULL,
  [J0183] [varchar](4) NULL,
  [J0205] [varchar](4) NULL,
  [J0210] [datetime] NULL,
  [J0218] [varchar](1) NULL,
  [J0219] [datetime] NULL,
  [J0334] [datetime] NULL,
  [J0340] [datetime] NULL,
  [J0360] [datetime] NULL,
  [J0399] [datetime] NULL,
  [J0459] [varchar](1) NULL,
  [J0675] [varchar](1) NULL,
  [J0926] [varchar](4) NULL,
  [J0927] [varchar](4) NULL,
  [J0048_DA] [varchar](10) NULL,
  [J0274_DA] [varchar](4) NULL,
  [J0275_DA] [varchar](4) NULL,
  [J0279_DA] [varchar](2) NULL,
  [J0048_DC] [varchar](10) NULL,
  [J0274_DC] [varchar](4) NULL,
  [J0275_DC] [varchar](4) NULL,
  [J0279_DC] [varchar](2) NULL,
  [J0048_MO] [varchar](10) NULL,
  [J0274_MO] [varchar](4) NULL,
  [J0275_MO] [varchar](4) NULL,
  [J0279_MO] [varchar](2) NULL,
  [J0093] [datetime] NULL,
  [LAST_UPD] [datetime] NOT NULL CONSTRAINT [DF__AGENT__LAST_UPD__060DEAE8]  DEFAULT (getdate()),
  [J0459_DA] [varchar](1) NOT NULL CONSTRAINT [DF__AGENT__J0459_DA__07020F21]  DEFAULT ('E'),
  [J0459_DC] [varchar](1) NOT NULL CONSTRAINT [DF__AGENT__J0459_DC__07F6335A]  DEFAULT ('E'),
  [J0459_MO] [varchar](1) NOT NULL CONSTRAINT [DF__AGENT__J0459_MO__08EA5793]  DEFAULT ('E'),
  [J1016_DA] [char](1) NULL,
  [J1016_DC] [char](1) NULL,
  [J1016_MO] [char](1) NULL,
 CONSTRAINT [SYS_C0019226] PRIMARY KEY CLUSTERED
(
  [AGENT_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[AGENT_HISTORY]    Script Date: 12/17/2010 11:49:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENT_HISTORY]') AND type in (N'U'))
DROP TABLE [dbo].[AGENT_HISTORY]


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[AGENT_HISTORY]    Script Date: 12/17/2010 11:49:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENT_HISTORY](
  [AGENT_HISTORY_PK] [numeric](38, 0) IDENTITY(1,1) NOT NULL,
  [MPAN_LNK] [numeric](38, 0) NOT NULL,
  [AGENT_ID] [char](4) NOT NULL,
  [AGENT_ROLE_CODE] [char](1) NOT NULL,
  [AGENT_EFD] [datetime] NOT NULL,
  [AGENT_ETD] [datetime] NOT NULL,
  [REASON_FOR_CHANGE] [varchar](4) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL CONSTRAINT [DF_AGENT_HISTORY_LAST_UPD]  DEFAULT (getdate()),
 CONSTRAINT [SYS_C0019234] PRIMARY KEY CLUSTERED
(
  [AGENT_HISTORY_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[MPAN]    Script Date: 12/17/2010 11:50:53 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MPAN]') AND type in (N'U'))
DROP TABLE [dbo].[MPAN]


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[MPAN]    Script Date: 12/17/2010 11:51:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MPAN](
  [UNIQ_ID] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [J0003] [varchar](13) NOT NULL,
  [DISTRIBUTOR] [varchar](4) NULL,
  [J0031] [varchar](10) NULL,
  [J0049] [datetime] NULL,
  [J0066] [varchar](2) NULL,
  [J0071] [numeric](11, 0) NULL CONSTRAINT [DF__MPAN__J0071__656C112C]  DEFAULT ((0)),
  [J0076] [varchar](4) NULL,
  [J0080] [varchar](1) NULL,
  [J0081] [varchar](16) NULL,
  [J0082] [varchar](1) NULL,
  [J0084] [varchar](4) NULL,
  [J0117] [datetime] NULL,
  [J0147] [numeric](11, 0) NULL CONSTRAINT [DF__MPAN__J0147__66603565]  DEFAULT ((0)),
  [J0215] [varchar](1) NULL,
  [J0263] [varchar](10) NULL,
  [J0297] [datetime] NULL,
  [J0300] [datetime] NULL,
  [J0301] [datetime] NULL,
  [J0306] [datetime] NULL,
  [J0307] [datetime] NULL,
  [J0308] [datetime] NULL,
  [J0473] [datetime] NULL,
  [J0658] [datetime] NULL,
  [J0923] [varchar](4) NULL,
  [J0924] [datetime] NULL,
  [J0925] [datetime] NULL,
  [J0928] [datetime] NULL,
  [J1036] [varchar](40) NULL,
  [J1037] [varchar](40) NULL,
  [J1038] [varchar](40) NULL,
  [J1039] [varchar](40) NULL,
  [J1040] [varchar](40) NULL,
  [J1041] [varchar](40) NULL,
  [J1042] [varchar](40) NULL,
  [J1043] [varchar](40) NULL,
  [J1044] [varchar](40) NULL,
  [J1194] [varchar](4) NULL,
  [J1628] [varchar](11) NULL,
  [J1647] [datetime] NULL,
  [J0090] [datetime] NULL,
  [J0220] [numeric](11, 0) NULL,
  [J0757] [varchar](10) NULL,
  [SUPPLIER_ID] [varchar](4) NULL,
  [J0821] [datetime] NULL,
  [IBT_LNK] [numeric](36, 0) NULL CONSTRAINT [DF__MPAN__IBT_LNK__6754599E]  DEFAULT ((0)),
  [J0093] [datetime] NULL,
  [LAST_UPD] [datetime] NOT NULL CONSTRAINT [DF__MPAN__LAST_UPD__68487DD7]  DEFAULT (getdate()),
  [X0210] [varchar](2) NULL,
  [X0211] [varchar](15) NULL,
  [X0213] [char](3) NOT NULL CONSTRAINT [DF__MPAN__X0213__693CA210]  DEFAULT ('000'),
  [J1687] [varchar](1) NULL,
  [J1689] [varchar](1) NULL,
  [X0214] [varchar](1) NULL CONSTRAINT [DF__MPAN__X0214__6A30C649]  DEFAULT ('F'),
  [X0219] [varchar](1) NULL CONSTRAINT [DF__MPAN__X0219__6B24EA82]  DEFAULT ('F'),
 CONSTRAINT [PK_UNIQ_ID] PRIMARY KEY CLUSTERED
(
  [UNIQ_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF


USE [CUSTOMER_TEST]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CUSTOMER_MPAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[CUSTOMER]'))
ALTER TABLE [dbo].[CUSTOMER] DROP CONSTRAINT [FK_CUSTOMER_MPAN]
GO
USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 12/17/2010 11:55:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMER]') AND type in (N'U'))
DROP TABLE [dbo].[CUSTOMER]


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 12/17/2010 13:27:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CUSTOMER](
  [CUSTOMER_PK] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [MPAN_LNK] [numeric](36, 0) NOT NULL,
  [CUST_ETD] [datetime] NULL,
  [J0375] [varchar](100) NULL,
  [J0489] [varchar](50) NULL,
  [J0490] [varchar](14) NULL,
  [J0491] [varchar](14) NULL,
  [J0692] [varchar](40) NULL,
  [J0693] [varchar](10) NULL,
  [J0694] [datetime] NULL,
  [J0846] [datetime] NULL,
  [J0851] [varchar](50) NULL,
  [J0852] [varchar](14) NULL,
  [J1011] [numeric](11, 0) NULL,
  [J1046] [varchar](40) NULL,
  [J1047] [varchar](40) NULL,
  [J1048] [varchar](40) NULL,
  [J1049] [varchar](40) NULL,
  [J1050] [varchar](40) NULL,
  [J1051] [varchar](40) NULL,
  [J1052] [varchar](40) NULL,
  [J1053] [varchar](40) NULL,
  [J1054] [varchar](40) NULL,
  [X0004] [varchar](1) NULL,
  [X0005] [varchar](200) NULL,
  [X0002] [varchar](1) NULL,
  [X0003] [varchar](1) NULL,
  [X0007] [varchar](1) NULL,
  [X0016] [varchar](2) NULL,
  [X0017] [varchar](20) NULL,
  [ALT_X0016] [varchar](2) NULL,
  [J0566] [varchar](10) NULL,
  [J1674] [varchar](1) NULL,
  [LAST_UPD] [datetime] NOT NULL CONSTRAINT [DF__CUSTOMER__LAST_U__1CF15040]  DEFAULT (getdate()),
 CONSTRAINT [SYS_C0019263] PRIMARY KEY CLUSTERED
(
  [CUSTOMER_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[CUSTOMER]  WITH NOCHECK ADD  CONSTRAINT [FK_CUSTOMER_MPAN] FOREIGN KEY([MPAN_LNK])
REFERENCES [dbo].[MPAN] ([UNIQ_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_MPAN]


USE [CUSTOMER_TEST]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMERNOTES]') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTES]'))
ALTER TABLE [dbo].[NOTES] DROP CONSTRAINT [CUSTOMERNOTES]
GO
USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[NOTES]    Script Date: 12/17/2010 13:29:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NOTES]') AND type in (N'U'))
DROP TABLE [dbo].[NOTES]


USE [CUSTOMER_TEST]
GO
/****** Object:  Table [dbo].[NOTES]    Script Date: 12/17/2010 13:29:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NOTES](
  [NOTE_PK] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [MPAN_LNK] [numeric](36, 0) NULL CONSTRAINT [DF__NOTES__MPAN_LNK__74AE54BC]  DEFAULT ((0)),
  [CUSTOMER_LNK] [numeric](36, 0) NULL CONSTRAINT [DF__NOTES__CUSTOMER___75A278F5]  DEFAULT ((0)),
  [NOTES] [varchar](1000) NULL,
  [DATE_] [datetime] NULL,
  [LAST_UPD] [datetime] NOT NULL CONSTRAINT [DF__NOTES__LAST_UPD__76969D2E]  DEFAULT (getdate()),
  [CREATED_BY] [varchar](50) NULL,
  [SUMMARY] [varchar](50) NULL,
 CONSTRAINT [SYS_C0019380] PRIMARY KEY CLUSTERED
(
  [NOTE_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[NOTES]  WITH NOCHECK ADD  CONSTRAINT [CUSTOMERNOTES] FOREIGN KEY([CUSTOMER_LNK])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_PK])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NOTES] CHECK CONSTRAINT [CUSTOMERNOTES]


USE [CUSTOMER_TEST]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[METER]') AND type in (N'U'))
DROP TABLE [dbo].[METER]


USE [CUSTOMER_TEST]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[METER](
  [METER_PK] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL  DEFAULT (getdate()),
  [MPAN_LNK] [numeric](36, 0) NOT NULL,
  [J0004] [varchar](10) NULL,
  [J0428] [varchar](20) NULL,
  [J1254] [datetime] NULL  DEFAULT (getdate()),
  [ETD_MSID] [datetime] NULL  DEFAULT (getdate()),
  [J0483] [varchar](5) NULL,

 CONSTRAINT [SYS_C0019339] PRIMARY KEY CLUSTERED
(
  [METER_PK] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF



USE [CUSTOMER_TEST]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[METER_REGISTER]') AND type in (N'U'))
DROP TABLE [dbo].[METER_REGISTER]


USE [CUSTOMER_TEST]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[METER_REGISTER](
  [METER_REG_PK] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL  DEFAULT (getdate()),
  [METER_FK] [numeric](36, 0) NOT NULL,
  [EFD_ID] [datetime] NOT NULL  DEFAULT (getdate()),
  [ETD_ID] [datetime] NOT NULL  DEFAULT (getdate()),
  [J0010] [varchar](1000) NULL,
  [J0103] [varchar](100) NULL,
  [J0474] [varchar](10) NULL,

 CONSTRAINT [SYS_C0020000] PRIMARY KEY CLUSTERED
(
  [METER_REG_PK] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF




USE [CUSTOMER_TEST]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[METER_REG_READING]') AND type in (N'U'))
DROP TABLE [dbo].[METER_REG_READING]


USE [CUSTOMER_TEST]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[METER_REG_READING](
  [MET_REG_READ] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL  DEFAULT (getdate()),
  [METER_REG_FK] [numeric](36, 0) NOT NULL,
  [J0016] [datetime] NOT NULL  DEFAULT (getdate()),
  [DATE_RECEIVED] [datetime] NOT NULL  DEFAULT (getdate()),
  [J0040] [float] NULL,
  [FLOW_RECEIVED] [varchar](100) NULL,

 CONSTRAINT [SYS_C0020001] PRIMARY KEY CLUSTERED
(
  [MET_REG_READ] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF





USE [CUSTOMER_TEST]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AREGI_PROCESS]') AND type in (N'U'))
DROP TABLE [dbo].[AREGI_PROCESS]


USE [CUSTOMER_TEST]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AREGI_PROCESS](
  [AR_PROC_PK] [numeric](36, 0) IDENTITY(1,1) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL  DEFAULT (getdate()),
  [MPAN_LNK] [numeric](36, 0) NOT NULL,
  [D0268_RECEIVED] [datetime] NULL  DEFAULT (getdate()),
  [D0268_DUP_RECEIVED] [datetime] NULL  DEFAULT (getdate()),
  [D0150_RECEIVED] [datetime] NULL  DEFAULT (getdate()),

 CONSTRAINT [SYS_C0020002] PRIMARY KEY CLUSTERED
(
  [AR_PROC_PK] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF

--create AFMSWEB_USER table

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_USER]    Script Date: 07/04/2011 13:18:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AFMSWEB_USER](
  [USER_PK] [numeric](36, 0) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL,
  [USERNAME] [varchar](25) NOT NULL,
  [PASSWORD] [varchar](32) NOT NULL,
  [ENABLED] [numeric](1, 0) NOT NULL,
  [EMAILADDRESS] [varchar](50) NULL,
  [END_DATE] [datetime] NULL,
  [PHONENUMBER] [varchar](250) NULL,
 CONSTRAINT [SYS_C0021552] PRIMARY KEY CLUSTERED
(
  [USER_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


-- create AFMSWEB_URL
USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_URL]    Script Date: 07/07/2011 16:42:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AFMSWEB_URL](
  [URL_PK] [numeric](36, 0) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL,
  [URL] [varchar](100) NOT NULL,
  [DESCRIPTION] [varchar](100) NULL,
  [ALLOW_BY_DEFAULT] [numeric](1, 0) NULL,
 CONSTRAINT [SYS_C0021546] PRIMARY KEY CLUSTERED
(
  [URL_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AFMSWEB_URL] ADD  CONSTRAINT [DF__AFMSWEB_U__ALLOW__03317E3D]  DEFAULT ((0)) FOR [ALLOW_BY_DEFAULT]
GO

-- create AFMSWEB_URLGROUP
USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_URLGROUP]    Script Date: 07/07/2011 16:45:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AFMSWEB_URLGROUP](
  [URLGROUP_PK] [numeric](36, 0) NOT NULL,
  [CODE] [nvarchar](50) NOT NULL,
  [DESCRIPTION] [nvarchar](100) NOT NULL,
  [ALLOW_BY_DEFAULT] [numeric](1, 0) NOT NULL,
  [ALWAYS_REQUIRED] [numeric](1, 0) NOT NULL,
  [LAST_UPD] [datetime] NOT NULL,
 CONSTRAINT [PK_AFMSWEB_URLGROUP] PRIMARY KEY CLUSTERED
(
  [URLGROUP_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-- create AFMSWEB_URL_URLGROUP
USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_URL_URLGROUP]    Script Date: 07/07/2011 16:45:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AFMSWEB_URL_URLGROUP](
  [URL_FK] [numeric](36, 0) NOT NULL,
  [URLGROUP_FK] [numeric](36, 0) NOT NULL,
 CONSTRAINT [PK_AFMSWEB_URL_URLGROUP] PRIMARY KEY CLUSTERED
(
  [URL_FK] ASC,
  [URLGROUP_FK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AFMSWEB_URL_URLGROUP]  WITH CHECK ADD  CONSTRAINT [FK_URL_URLGROUP_URL] FOREIGN KEY([URL_FK])
REFERENCES [dbo].[AFMSWEB_URL] ([URL_PK])
GO

ALTER TABLE [dbo].[AFMSWEB_URL_URLGROUP] CHECK CONSTRAINT [FK_URL_URLGROUP_URL]
GO

ALTER TABLE [dbo].[AFMSWEB_URL_URLGROUP]  WITH CHECK ADD  CONSTRAINT [FK_URL_URLGROUP_URLGROUP] FOREIGN KEY([URLGROUP_FK])
REFERENCES [dbo].[AFMSWEB_URLGROUP] ([URLGROUP_PK])
GO

ALTER TABLE [dbo].[AFMSWEB_URL_URLGROUP] CHECK CONSTRAINT [FK_URL_URLGROUP_URLGROUP]
GO

