USE [master]
GO
/****** Object:  Database [CUSTOMER_TEST]    Script Date: 12/17/2010 14:48:55 ******/
CREATE DATABASE [CUSTOMER_TEST] ON  PRIMARY
( NAME = N'CUSTOMER_TEST', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\CUSTOMER_TEST.mdf' , SIZE = 1150016KB , MAXSIZE = UNLIMITED, FILEGROWTH = 256000KB )
 LOG ON
( NAME = N'CUSTOMER_TEST_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\CUSTOMER_TEST.ldf' , SIZE = 129280KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'CUSTOMER_TEST', @new_cmptlevel=80
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CUSTOMER_TEST].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [CUSTOMER_TEST] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET ANSI_NULLS OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET ANSI_PADDING OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET ARITHABORT OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [CUSTOMER_TEST] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [CUSTOMER_TEST] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [CUSTOMER_TEST] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET  DISABLE_BROKER
GO
ALTER DATABASE [CUSTOMER_TEST] SET AUTO_UPDATE_STATISTICS_ASYNC ON
GO
ALTER DATABASE [CUSTOMER_TEST] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [CUSTOMER_TEST] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [CUSTOMER_TEST] SET  READ_WRITE
GO
ALTER DATABASE [CUSTOMER_TEST] SET RECOVERY FULL
GO
ALTER DATABASE [CUSTOMER_TEST] SET  MULTI_USER
GO
ALTER DATABASE [CUSTOMER_TEST] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [CUSTOMER_TEST] SET DB_CHAINING OFF