--drop Agent table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AGENT__LAST_UPD__060DEAE8]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AGENT] DROP CONSTRAINT [DF__AGENT__LAST_UPD__060DEAE8]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AGENT__J0459_DA__07020F21]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AGENT] DROP CONSTRAINT [DF__AGENT__J0459_DA__07020F21]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AGENT__J0459_DC__07F6335A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AGENT] DROP CONSTRAINT [DF__AGENT__J0459_DC__07F6335A]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AGENT__J0459_MO__08EA5793]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AGENT] DROP CONSTRAINT [DF__AGENT__J0459_MO__08EA5793]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AGENT]    Script Date: 07/04/2011 10:21:56 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENT]') AND type in (N'U'))
DROP TABLE [dbo].[AGENT]
GO

--drop AGENT_HISTORY table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_AGENT_HISTORY_LAST_UPD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AGENT_HISTORY] DROP CONSTRAINT [DF_AGENT_HISTORY_LAST_UPD]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AGENT_HISTORY]    Script Date: 07/04/2011 10:22:57 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENT_HISTORY]') AND type in (N'U'))
DROP TABLE [dbo].[AGENT_HISTORY]
GO

--drop AREGI_PROCESS table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AREGI_PRO__LAST___33BFA6FF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AREGI_PROCESS] DROP CONSTRAINT [DF__AREGI_PRO__LAST___33BFA6FF]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AREGI_PRO__D0268__34B3CB38]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AREGI_PROCESS] DROP CONSTRAINT [DF__AREGI_PRO__D0268__34B3CB38]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AREGI_PRO__D0268__35A7EF71]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AREGI_PROCESS] DROP CONSTRAINT [DF__AREGI_PRO__D0268__35A7EF71]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AREGI_PROCESS]    Script Date: 07/04/2011 10:23:45 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AREGI_PROCESS]') AND type in (N'U'))
DROP TABLE [dbo].[AREGI_PROCESS]
GO

--drop METER table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER__LAST_UPD__2759D01A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER] DROP CONSTRAINT [DF__METER__LAST_UPD__2759D01A]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[METER]    Script Date: 07/04/2011 10:24:34 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[METER]') AND type in (N'U'))
DROP TABLE [dbo].[METER]
GO

--drop METER_REG_READING table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER_REG__LAST___2EFAF1E2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER_REG_READING] DROP CONSTRAINT [DF__METER_REG__LAST___2EFAF1E2]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER_REG__J0016__2FEF161B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER_REG_READING] DROP CONSTRAINT [DF__METER_REG__J0016__2FEF161B]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER_REG__DATE___30E33A54]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER_REG_READING] DROP CONSTRAINT [DF__METER_REG__DATE___30E33A54]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[METER_REG_READING]    Script Date: 07/04/2011 10:25:47 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[METER_REG_READING]') AND type in (N'U'))
DROP TABLE [dbo].[METER_REG_READING]
GO

--drop METER_REGISTER table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER_REG__LAST___2A363CC5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER_REGISTER] DROP CONSTRAINT [DF__METER_REG__LAST___2A363CC5]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER_REG__EFD_I__2B2A60FE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER_REGISTER] DROP CONSTRAINT [DF__METER_REG__EFD_I__2B2A60FE]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__METER_REG__ETD_I__2C1E8537]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[METER_REGISTER] DROP CONSTRAINT [DF__METER_REG__ETD_I__2C1E8537]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[METER_REGISTER]    Script Date: 07/04/2011 10:26:08 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[METER_REGISTER]') AND type in (N'U'))
DROP TABLE [dbo].[METER_REGISTER]
GO

--drop MPAN table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__J0071__656C112C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__J0071__656C112C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__J0147__66603565]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__J0147__66603565]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__IBT_LNK__6754599E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__IBT_LNK__6754599E]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__LAST_UPD__68487DD7]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__LAST_UPD__68487DD7]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__X0213__693CA210]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__X0213__693CA210]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__X0214__6A30C649]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__X0214__6A30C649]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__MPAN__X0219__6B24EA82]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MPAN] DROP CONSTRAINT [DF__MPAN__X0219__6B24EA82]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[MPAN]    Script Date: 07/04/2011 10:26:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MPAN]') AND type in (N'U'))
DROP TABLE [dbo].[MPAN]
GO

--drop NOTES table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMERNOTES]') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTES]'))
ALTER TABLE [dbo].[NOTES] DROP CONSTRAINT [CUSTOMERNOTES]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__NOTES__MPAN_LNK__74AE54BC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[NOTES] DROP CONSTRAINT [DF__NOTES__MPAN_LNK__74AE54BC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__NOTES__CUSTOMER___75A278F5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[NOTES] DROP CONSTRAINT [DF__NOTES__CUSTOMER___75A278F5]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__NOTES__LAST_UPD__76969D2E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[NOTES] DROP CONSTRAINT [DF__NOTES__LAST_UPD__76969D2E]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[NOTES]    Script Date: 07/04/2011 10:27:03 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NOTES]') AND type in (N'U'))
DROP TABLE [dbo].[NOTES]
GO

--drop CUSTOMER table

USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CUSTOMER_MPAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[CUSTOMER]'))
ALTER TABLE [dbo].[CUSTOMER] DROP CONSTRAINT [FK_CUSTOMER_MPAN]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__CUSTOMER__LAST_U__1CF15040]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CUSTOMER] DROP CONSTRAINT [DF__CUSTOMER__LAST_U__1CF15040]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 07/04/2011 10:24:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMER]') AND type in (N'U'))
DROP TABLE [dbo].[CUSTOMER]
GO


-- drop AFMSWEB_USER table
USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_USER]    Script Date: 07/07/2011 17:02:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AFMSWEB_USER]') AND type in (N'U'))
DROP TABLE [dbo].[AFMSWEB_USER]
GO

-- drop AFMSWEB_URL table
USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__AFMSWEB_U__ALLOW__03317E3D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[AFMSWEB_URL] DROP CONSTRAINT [DF__AFMSWEB_U__ALLOW__03317E3D]
END

GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_URL]    Script Date: 07/07/2011 17:03:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AFMSWEB_URL]') AND type in (N'U'))
DROP TABLE [dbo].[AFMSWEB_URL]
GO


-- drop AFMSWEB_URL_URLGROUP table
USE [CUSTOMER_TEST]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_URL_URLGROUP_URL]') AND parent_object_id = OBJECT_ID(N'[dbo].[AFMSWEB_URL_URLGROUP]'))
ALTER TABLE [dbo].[AFMSWEB_URL_URLGROUP] DROP CONSTRAINT [FK_URL_URLGROUP_URL]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_URL_URLGROUP_URLGROUP]') AND parent_object_id = OBJECT_ID(N'[dbo].[AFMSWEB_URL_URLGROUP]'))
ALTER TABLE [dbo].[AFMSWEB_URL_URLGROUP] DROP CONSTRAINT [FK_URL_URLGROUP_URLGROUP]
GO

USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_URL_URLGROUP]    Script Date: 07/07/2011 17:05:29 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AFMSWEB_URL_URLGROUP]') AND type in (N'U'))
DROP TABLE [dbo].[AFMSWEB_URL_URLGROUP]
GO


-- drop AFMSWEB_URLGROUP table
USE [CUSTOMER_TEST]
GO

/****** Object:  Table [dbo].[AFMSWEB_URLGROUP]    Script Date: 07/07/2011 17:05:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AFMSWEB_URLGROUP]') AND type in (N'U'))
DROP TABLE [dbo].[AFMSWEB_URLGROUP]
GO