CREATE TABLESPACE "CUSTOMER_TEST"
LOGGING
DATAFILE 'C:\oracle\product\10.2.0\oradata\utpc02\customer_test.ora'
SIZE 10m
AUTOEXTEND ON
NEXT 10m MAXSIZE 50m
EXTENT MANAGEMENT LOCAL;
commit;

CREATE USER "CUSTOMER_TEST"
IDENTIFIED BY "formfill" DEFAULT TABLESPACE "CUSTOMER_TEST"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;
commit;

GRANT "CONNECT" TO "CUSTOMER_TEST";
GRANT "RESOURCE" TO "CUSTOMER_TEST";