--Hint: sql files need to be in the same directory as parms.oracle.multiscript.install.sql to run successfully
@upgrade/0000.oracle.install.create_version_table.sql
@upgrade/0001.oracle.install.createParmsTables.sql
@upgrade/0002.oracle.install.createParmsStandingData.sql
@upgrade/0003.oracle.install.createParmsSp04Tables.sql
@upgrade/0004.oracle.install.createGspDefinition.sql
@upgrade/0005.oracle.install.createP0028ErrorTables.sql
@upgrade/0006.oracle.install.renameMeterRegisterid.sql
@upgrade/0007.oracle.install.create.P0028FileData.table.sql
@upgrade/0008.oracle.install.updateListOfSerials.sql
@upgrade/0009.oracle.install.addColumnsToGSP.sql
@upgrade/0010.oracle.install.addSecurityChanges.sql
@upgrade/0011.oracle.install.add.has.errors.column.to.p0028.file.table.sql
@upgrade/0012.oracle.install.newSerials.sql
@upgrade/0013.oracle.install.createParmsAuditTable.sql
@upgrade/0014.oracle.install.updateParmsSp04Tables.sql
@upgrade/0015.oracle.install.updateParmsSp04Tables.sql
@upgrade/0016.oracle.install.sp04.enhancements.sql
@upgrade/0017.oracle.install.quartz.tables.sql
@upgrade/0018.oracle.install.addP0028UploadWarnings.sql
@upgrade/0019.oracle.install.populateParmsSupplier.sql
@upgrade/0020.oracle.install.addCalculatedStandardsToSp04FromAfmsMpanTable.sql
@upgrade/0021.oracle.install.removeGspGroupU.sql
@upgrade/0022.oracle.install.addAfmsMpanEfdAndEtdColumnsToSp04FromAfmsMpanTable.sql
@upgrade/0023.oracle.install.addMaxDemandColumnToSp04FromAfmsMpansTable.sql
@upgrade/0024.oracle.install.renameColumnsToGSP.sql
@upgrade/0025.oracle.install.addHalfHourlyQualifyingMpansReport.sql
@upgrade/0026.oracle.install.alterSp04FromAfmsMpansTableColumnMeterRegisterFk.sql