--Hint: sql files need to be in the same directory as parms.oracle.multiscript.backout.sql to run successfully
@backout/0026.oracle.backout.alterSp04FromAfmsMpansTableColumnMeterRegisterFk.sql
@backout/0025.oracle.backout.addHalfHourlyQualifyingMpansReport.sql
@backout/0024.oracle.backout.renameColumnsToGSP.sql
@backout/0023.oracle.backout.addMaxDemandColumnToSp04FromAfmsMpansTable.sql
@backout/0022.oracle.backout.addAfmsMpanEfdAndEtdColumnsToSp04FromAfmsMpanTable.sql
@backout/0021.oracle.backout.removeGspGroupU.sql
@backout/0020.oracle.backout.addCalculatedStandardsToSp04FromAfmsMpanTable.sql
@backout/0019.oracle.backout.populateParmeSupplier.sql
@backout/0018.oracle.backout.addP0028UploadWarnings.sql
@backout/0017.oracle.backout.quartz.tables.sql
@backout/0016.oracle.backout.sp04.enhancements.sql
@backout/0015.oracle.backout.addCurrentMeasurementClassColumnToParmsP0028DataTable.sql
@backout/0014.oracle.backout.addMpanUniqIdColumnToParmsP0028DataTable.sql
@backout/0013.oracle.backout.createParmsAuditTable.sql
@backout/0012.oracle.backout.newSerials.sql
@backout/0011.oracle.backout.add.has.errors.column.to.p0028.file.table.sql
@backout/0010.oracle.backout.addSecurityChanges.sql
@backout/0009.oracle.backout.addColumnsToGSP.sql
@backout/0008.oracle.backout.updateListOfSerials.sql
@backout/0007.oracle.backout.P0028FileData.table.sql
@backout/0006.oracle.backout.renameMeterRegisterid.sql
@backout/0005.oracle.backout.createP0028ErrorTables.sql
@backout/0004.oracle.backoutGspDefinition.sql
@backout/0003.oracle.backout.dropParmsSp04Tables.sql
@backout/0002.oracle.backout.ParmsStandingData.sql
@backout/0001.oracle.backout.createParmsTables.sql
@backout/0000.oracle.backout.version.sql